version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ".env"
    ports:
      - "8080:5001"
    depends_on:
      - pg_operation
  pg_operation:
    image: postgres:12
    env_file:
    - ".env"
    ports:
      - "5433:5432"

