"""empty message

Revision ID: 21d359fbf4d4
Revises: 626e66ab6378
Create Date: 2023-03-30 23:47:05.886366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21d359fbf4d4'
down_revision = '626e66ab6378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurses',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('second_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('surgeons',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('second_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('_password', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operation_nurse_table',
    sa.Column('operation_id', sa.String(length=300), nullable=True),
    sa.Column('nuse_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['nuse_id'], ['nurses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE')
    )
    op.create_table('operation_surgeon_table',
    sa.Column('operation_id', sa.String(length=300), nullable=False),
    sa.Column('surgeon_id', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surgeon_id'], ['surgeons.id'], ondelete='CASCADE')
    )
    op.drop_table('operation')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('_password', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('name', name='user_name_key')
    )
    op.create_table('operation',
    sa.Column('id', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('operators', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='operation_pkey')
    )
    op.drop_table('operation_surgeon_table')
    op.drop_table('operation_nurse_table')
    op.drop_table('users')
    op.drop_table('surgeons')
    op.drop_table('operations')
    op.drop_table('nurses')
    # ### end Alembic commands ###
