"""empty message

Revision ID: 2ea343f35732
Revises: ec18039be23a
Create Date: 2023-03-31 01:18:43.087028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea343f35732'
down_revision = 'ec18039be23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nurses', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('second_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('surgeons', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('second_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgeons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.alter_column('second_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('nurses', schema=None) as batch_op:
        batch_op.alter_column('second_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
