"""empty message

Revision ID: 626e66ab6378
Revises: 
Create Date: 2023-03-15 20:55:15.671069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626e66ab6378'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('operators', sa.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('_password', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('operation')
    # ### end Alembic commands ###
